import { Injectable, signal } from '@angular/core';
import type { Dinamica } from '../models/dinamica';

@Injectable({ providedIn: 'root' })
export class DinamicasService {
  readonly dinamicas = signal<Dinamica[]>(this.cargarDinamicas());

  getPorId(id: string): Dinamica | undefined {
    return this.dinamicas().find(d => d.id === id);
  }

  getPorCategoria(categoria: string): Dinamica[] {
    return this.dinamicas().filter(d => d.categoria === categoria);
  }

  aleatoria(): Dinamica {
    const lista = this.dinamicas();
    return lista[Math.floor(Math.random() * lista.length)];
  }

  private cargarDinamicas(): Dinamica[] {
    return [
      {
        id: 'nudo-humano',
        nombre: 'El Nudo Humano',
        categoria: 'colaboracion',
        descripcion: 'Los participantes forman un círculo y se toman de las manos de forma enredada, luego deben desenredarse sin soltarse.',
        objetivo: 'Fomentar la colaboración, comunicación no verbal y resolución de problemas en equipo.',
        duracion: 15,
        participantesMin: 6,
        participantesMax: 20,
        materiales: [],
        instrucciones: [
          'Todos los participantes se paran en un círculo muy cerrado.',
          'Cada persona extiende su mano derecha y toma la mano de otra persona que no esté a su lado.',
          'Luego extienden la mano izquierda y toman la mano de una persona diferente.',
          'Sin soltarse, deben trabajar juntos para desenredar el nudo hasta formar un círculo nuevamente.',
          'Pueden pasar por encima o por debajo de los brazos, pero nunca soltarse las manos.',
        ],
        consejos: [
          'Si el nudo parece imposible, permite un descanso de 30 segundos para replantear la estrategia.',
          'Anima a los participantes a comunicarse claramente.',
          'Para grupos grandes, divide en equipos más pequeños.',
        ],
        icono: '🤝',
      },
      {
        id: 'isla-desierta',
        nombre: 'La Isla Desierta',
        categoria: 'problemas',
        descripcion: 'El equipo está "varado" y debe acordar qué 5 objetos llevarían para sobrevivir.',
        objetivo: 'Practicar la toma de decisiones en grupo, negociación y priorización.',
        duracion: 25,
        participantesMin: 4,
        participantesMax: 30,
        materiales: ['Lista de 20 objetos para elegir', 'Papel y lápiz para cada equipo'],
        instrucciones: [
          'Presenta la situación: "Han naufragado y están en una isla desierta. Solo pueden llevar 5 objetos."',
          'Entrega la lista de 20 objetos disponibles a cada persona.',
          'Cada persona selecciona individualmente sus 5 objetos (5 minutos).',
          'En equipos de 4-6 personas, deben llegar a un consenso sobre los 5 objetos del equipo (15 minutos).',
          'Cada equipo presenta su lista final y justifica sus elecciones.',
        ],
        consejos: [
          'Observa quién toma el rol de líder en cada grupo.',
          'Fomenta que todos participen en la discusión.',
          'Debriefing: ¿Cómo fue el proceso de toma de decisiones?',
        ],
        icono: '🏝️',
      },
      {
        id: 'globos-cooperativos',
        nombre: 'Globos Cooperativos',
        categoria: 'colaboracion',
        descripcion: 'Equipos compiten por mantener sus globos en el aire mientras colaboran internamente.',
        objetivo: 'Mejorar la coordinación, comunicación rápida y trabajo bajo presión.',
        duracion: 10,
        participantesMin: 4,
        participantesMax: 40,
        materiales: ['Globos (1 por cada 2 participantes)', 'Cronómetro'],
        instrucciones: [
          'Divide en equipos de 4-6 personas.',
          'Cada equipo recibe globos (1 globo por cada 2 personas).',
          'A la señal, todos deben mantener los globos en el aire golpeándolos.',
          'Nadie puede sostener un globo por más de 2 segundos.',
          'Si un globo toca el suelo, el equipo debe comenzar de nuevo.',
          'Gana el equipo que mantenga todos sus globos en el aire por más tiempo.',
        ],
        consejos: [
          'Para variar, prohíbe el uso de las manos en una ronda.',
          'Añade más globos progresivamente para aumentar la dificultad.',
          'Debriefing: ¿Cómo se organizaron? ¿Quién coordinó?',
        ],
        icono: '🎈',
      },
      {
        id: 'telefono-descompuesto',
        nombre: 'Teléfono Descompuesto en Equipo',
        categoria: 'comunicacion',
        descripcion: 'Un mensaje se transmite en cadena por el equipo, demostrando cómo la información se distorsiona.',
        objetivo: 'Demostrar la importancia de la comunicación clara y la escucha activa.',
        duracion: 15,
        participantesMin: 6,
        participantesMax: 30,
        materiales: ['Tarjetas con mensajes preparados'],
        instrucciones: [
          'Los participantes se colocan en fila o círculo.',
          'El primero lee un mensaje de una tarjeta.',
          'Susurra el mensaje al oído del siguiente participante, solo una vez.',
          'Cada persona repite el mensaje al siguiente, sin repetir ni preguntar.',
          'El último dice el mensaje en voz alta.',
          'Compara el mensaje final con el original.',
          'Repite el ejercicio permitiendo que cada persona repita el mensaje una vez.',
        ],
        consejos: [
          'Usa mensajes con números, nombres y detalles específicos.',
          'Contrasta los resultados con y sin la posibilidad de repetir.',
          'Debriefing: ¿Qué barreras de comunicación identificaron?',
        ],
        icono: '📞',
      },
      {
        id: 'torre-de-macarrones',
        nombre: 'Torre de Macarrones',
        categoria: 'creatividad',
        descripcion: 'Equipos compiten por construir la torre más alta usando solo espaguetis, cinta y malvaviscos.',
        objetivo: 'Estimular la creatividad, innovación y prototipado rápido bajo restricciones.',
        duracion: 30,
        participantesMin: 3,
        participantesMax: 24,
        materiales: ['20 espaguetis crudos por equipo', '1 metro de cinta adhesiva', '1 metro de cuerda', '1 malvavisco grande por equipo'],
        instrucciones: [
          'Divide en equipos de 3-4 personas.',
          'Entrega los materiales a cada equipo.',
          'Tienen 18 minutos para construir la torre más alta que pueda sostener el malvavisco en la punta.',
          'La torre debe ser autosoportable (no puede estar pegada a la mesa, silla, etc.).',
          'Al final, todos se alejan y se miden las torres.',
          'La torre más alta que sostenga el malvavisco gana.',
        ],
        consejos: [
          'Muestra el video TED Talk de Tom Wujec sobre el desafío del malvavisco.',
          'Anota qué estrategias usaron los equipos más exitosos.',
          'Debriefing: ¿Cómo iteraron? ¿Prototiparon o planificaron demasiado?',
        ],
        icono: '🍝',
      },
      {
        id: 'confianza-caida',
        nombre: 'La Caída de Confianza',
        categoria: 'confianza',
        descripcion: 'Una persona se deja caer hacia atrás confiando en que su equipo la atrapará.',
        objetivo: 'Construir confianza interpersonal y superar el miedo a delegar responsibility.',
        duracion: 20,
        participantesMin: 8,
        participantesMax: 20,
        materiales: [],
        instrucciones: [
          'Forma parejas o grupos de 6-8 personas.',
          'En parejas: Una persona se coloca detrás de la otra a 1 metro de distancia.',
          'La persona de adelante se deja caer hacia atrás, rígida como un tablón.',
          'La persona de atrás la atrapa por los hombros.',
          'En grupo: Una persona se para en una plataforma baja (20-30 cm) y se deja caer hacia atrás.',
          'El resto del equipo forma dos filas enfrentadas con los brazos extendidos para atraparla.',
        ],
        consejos: [
          'IMPORTANTE: Asegura que todos entiendan la técnica correcta para atrapar.',
          'Empieza con caídas pequeñas y aumenta gradualmente.',
          'Debriefing: ¿Cómo se sintieron al dejarse caer? ¿Qué se necesita para confiar?',
        ],
        icono: '🫱',
      },
      {
        id: 'sobrevivientes',
        nombre: 'Sobrevivientes',
        categoria: 'liderazgo',
        descripcion: 'El equipo debe elegir líderes y tomar decisiones críticas en un escenario de crisis simulado.',
        objetivo: 'Identificar estilos de liderazgo, practicar la delegación y la toma de decisiones bajo presión.',
        duracion: 35,
        participantesMin: 8,
        participantesMax: 30,
        materiales: ['Escenario de crisis impreso', 'Hoja de decisiones', 'Cronómetro'],
        instrucciones: [
          'Presenta el escenario: "Un desastre ha ocurrido y deben evacuar. Hay recursos limitados."',
          'Cada equipo debe elegir un líder en 2 minutos.',
          'El líder recibe la lista de recursos y personas.',
          'El equipo tiene 15 minutos para decidir: quién se salva, qué se lleva, orden de evacuación.',
          'Cada 5 minutos, introduce una crisis nueva (ej: "El clima empeora, pierden 2 recursos").',
          'El líder debe comunicar las decisiones finales y justificarlas.',
        ],
        consejos: [
          'Observa si el líder consulta al equipo o decide unilateralmente.',
          '¿Aparecieron líderes informales? ¿Cómo manejaron la presión?',
          'Debriefing: ¿Qué estilo de liderazgo funcionó mejor?',
        ],
        icono: '🚨',
      },
      {
        id: 'dos-verdades-mentira',
        nombre: 'Dos Verdades y una Mentira',
        categoria: 'icebreaker',
        descripcion: 'Cada persona comparte tres afirmaciones sobre sí misma; los demás adivinan cuál es la mentira.',
        objetivo: 'Romper el hielo, conocerse mejor y crear conexiones personales en el equipo.',
        duracion: 15,
        participantesMin: 4,
        participantesMax: 30,
        materiales: [],
        instrucciones: [
          'Cada participante piensa en 3 afirmaciones sobre sí mismo: 2 verdaderas y 1 falsa.',
          'Por turnos, cada persona dice sus 3 afirmaciones al grupo.',
          'El resto del equipo vota o discute cuál creen que es la mentira.',
          'La persona revela cuál era la mentira.',
          'Si alguien acierta, gana un punto. Sigue la siguiente persona.',
        ],
        consejos: [
          'Anima a que las afirmaciones sean interesantes o sorprendentes.',
          'El facilitador puede empezar como ejemplo.',
          'Para equipos grandes, divide en grupos más pequeños.',
        ],
        icono: '🎭',
      },
      {
        id: 'escape-room-equipo',
        nombre: 'Escape Room de Equipo',
        categoria: 'problemas',
        descripcion: 'El equipo debe resolver una serie de acertijos para "escapar" antes de que se acabe el tiempo.',
        objetivo: 'Desarrollar pensamiento crítico, colaboración y gestión del tiempo bajo presión.',
        duracion: 30,
        participantesMin: 4,
        participantesMax: 16,
        materiales: ['Sobres con acertijos', 'Candados o códigos', 'Cronómetro', 'Pistas de ayuda'],
        instrucciones: [
          'Prepara 5 acertijos o rompecabezas que deben resolverse en secuencia.',
          'Divide en equipos de 4 personas.',
          'Cada equipo comienza con el primer acertijo.',
          'Al resolverlo, obtienen la clave para el siguiente.',
          'Pueden pedir hasta 3 pistas durante el juego.',
          'Gana el equipo que resuelva todos los acertijos en el menor tiempo.',
        ],
        consejos: [
          'Ajusta la dificultad según el grupo.',
          'Asegúrate de que cada miembro del equipo tenga un rol.',
          'Debriefing: ¿Cómo distribuyeron las tareas? ¿Quién lideró?',
        ],
        icono: '🔐',
      },
      {
        id: 'dibujo-colaborativo',
        nombre: 'Dibujo Colaborativo a Ciegas',
        categoria: 'comunicacion',
        descripcion: 'Una persona describe una imagen y el equipo debe dibujarla sin verla, siguiendo solo instrucciones verbales.',
        objetivo: 'Mejorar la comunicación verbal precisa y la escucha activa.',
        duracion: 20,
        participantesMin: 4,
        participantesMax: 20,
        materiales: ['Imágenes simples impresas', 'Hojas blancas', 'Lápices o marcadores'],
        instrucciones: [
          'Una persona (el "descriptor") ve una imagen sin mostrarla a nadie.',
          'El descriptor da instrucciones verbales para que los demás dibujen la imagen.',
          'Los dibujantes no pueden hacer preguntas en la primera ronda.',
          'En la segunda ronda, los dibujantes pueden hacer preguntas.',
          'Compara los dibujos con el original en cada ronda.',
        ],
        consejos: [
          'Usa imágenes con formas geométricas primero, luego más complejas.',
          'Debriefing: ¿Cómo cambió la calidad cuando permitieron preguntas?',
          'Destaca la importancia del feedback bidireccional.',
        ],
        icono: '🎨',
      },
      {
        id: 'cadena-de-papel',
        nombre: 'Cadena de Papel Ilimitada',
        categoria: 'creatividad',
        descripcion: 'Con una sola hoja de papel y tijeras, el equipo debe crear la cadena más larga posible.',
        objetivo: 'Fomentar el pensamiento lateral, la experimentación y la optimización de recursos.',
        duracion: 15,
        participantesMin: 2,
        participantesMax: 20,
        materiales: ['1 hoja de papel A4 por equipo', 'Tijeras', 'Cinta métrica'],
        instrucciones: [
          'Entrega una hoja de papel y tijeras a cada equipo.',
          'Deben crear una cadena continua (cortando tiras y uniéndolas) con la hoja.',
          'Tienen 10 minutos para planificar y ejecutar.',
          'Al final, se miden las cadenas. La más larga gana.',
          'No pueden usar cinta adhesiva ni pegamento.',
        ],
        consejos: [
          'Hay una técnica de corte en espiral que maximiza la longitud.',
          'Observa si los equipos experimentan o se quedan con la primera idea.',
          'Debriefing: ¿Cómo llegaron a la solución óptima?',
        ],
        icono: '📄',
      },
      {
        id: 'cruce-del-rio',
        nombre: 'El Cruce del Río',
        categoria: 'colaboracion',
        descripcion: 'El equipo debe cruzar un "río" usando solo plataformas limitadas que deben moverse colectivamente.',
        objetivo: 'Practicar la planificación estratégica, coordinación y apoyo mutuo.',
        duracion: 25,
        participantesMin: 6,
        participantesMax: 20,
        materiales: ['Hojas de papel o tapetes (2 menos que participantes)', 'Cinta para marcar el río'],
        instrucciones: [
          'Marca dos líneas paralelas en el suelo (el río).',
          'Coloca "piedras" (hojas de papel) dentro del río.',
          'El equipo debe cruzar de un lado al otro pisando solo las piedras.',
          'Si alguien pisa fuera de una piedra, todo el equipo vuelve a empezar.',
          'Las piedras pueden moverse, pero siempre debe haber alguien tocándolas.',
          'Todos deben cruzar para ganar.',
        ],
        consejos: [
          'Aumenta la dificultad reduciendo el número de piedras.',
          'Prohíben hablar en una ronda para fomentar comunicación no verbal.',
          'Debriefing: ¿Cómo planificaron el cruce? ¿Ayudaron a los que tenían dificultades?',
        ],
        icono: '🌊',
      },
      {
        id: 'feedback-positivo',
        nombre: 'Ronda de Feedback Positivo',
        categoria: 'confianza',
        descripcion: 'Cada persona recibe comentarios positivos y genuinos de cada miembro del equipo.',
        objetivo: 'Fortalecer la confianza, autoestima y relaciones interpersonales en el equipo.',
        duracion: 20,
        participantesMin: 4,
        participantesMax: 16,
        materiales: ['Tarjetas o post-its'],
        instrucciones: [
          'Cada persona escribe en tarjetas algo positivo sobre cada compañero (cualidad, habilidad, aporte).',
          'Alternativa verbal: cada persona se sienta en el centro y recibe comentarios del círculo.',
          'Cada persona recibe sus tarjetas y las lee.',
          'Pueden compartir cómo se sintieron al recibir los comentarios.',
          'Opcional: crear un "muro de apreciación" con todas las tarjetas.',
        ],
        consejos: [
          'Los comentarios deben ser específicos y genuinos, no genéricos.',
          'Crea un ambiente seguro y de respeto.',
          'Debriefing: ¿Cómo nos hace sentir ser apreciados? ¿Cómo podemos hacer esto más seguido?',
        ],
        icono: '💚',
      },
      {
        id: 'construccion-ciega',
        nombre: 'Construcción a Ciegas',
        categoria: 'liderazgo',
        descripcion: 'Un líder debe guiar a su equipo con los ojos vendados para construir una estructura siguiendo un modelo.',
        objetivo: 'Practicar el liderazgo directivo, la comunicación clara y la confianza en las instrucciones.',
        duracion: 25,
        participantesMin: 6,
        participantesMax: 20,
        materiales: ['Bloques de construcción o LEGO', 'Vendas para los ojos', 'Estructura modelo'],
        instrucciones: [
          'Elige a un líder por equipo.',
          'El líder ve la estructura modelo; el resto del equipo tiene los ojos vendados.',
          'El líder da instrucciones verbales para que el equipo construya la estructura.',
          'El líder no puede tocar los bloques ni a los constructores.',
          'Al final, se destapan los ojos y comparan con el modelo.',
        ],
        consejos: [
          'Rotan los roles para que varios practiquen el liderazgo.',
          'Debriefing: ¿Qué hizo que las instrucciones fueran efectivas? ¿Cómo se sintió depender del líder?',
        ],
        icono: '🧱',
      },
      {
        id: 'historia-colectiva',
        nombre: 'Historia Colectiva',
        categoria: 'creatividad',
        descripcion: 'El equipo crea una historia improvisada donde cada persona añade una palabra o frase por turno.',
        objetivo: 'Estimular la creatividad colectiva, la escucha activa y la construcción sobre ideas de otros.',
        duracion: 15,
        participantesMin: 4,
        participantesMax: 20,
        materiales: [],
        instrucciones: [
          'El facilitador dice la primera palabra de una historia.',
          'Cada participante añade una palabra por turno para continuar la historia.',
          'Variante 1: Cada persona añade una frase completa.',
          'Variante 2: Se escribe la historia en un papel, doblándolo para que cada persona vea solo la última línea.',
          'Al final, se lee la historia completa.',
        ],
        consejos: [
          'Anima a ser creativos pero coherentes con la historia.',
          'Para equipos grandes, divide en grupos de 5-6.',
          'Graba la historia o escríbela para compartir después.',
        ],
        icono: '📖',
      },
      {
        id: 'globos-agua',
        nombre: 'Equilibrio de Agua',
        categoria: 'colaboracion',
        descripcion: 'El equipo debe transportar agua de un punto a otro usando solo recipientes que deben pasar colectivamente.',
        objetivo: 'Fomentar la coordinación, paciencia y trabajo en equipo preciso.',
        duracion: 20,
        participantesMin: 6,
        participantesMax: 24,
        materiales: ['Vasos o recipientes', 'Agua', 'Globos de agua', 'Baldes'],
        instrucciones: [
          'Forma equipos de 6 personas en fila.',
          'El primer miembro tiene un balde con agua.',
          'Deben pasar el agua hacia el final de la fila usando vasos pequeños.',
          'No pueden girar el cuerpo; solo pasar los vasos hacia atrás.',
          'Gana el equipo que más agua tenga al final en el balde vacío.',
          'Variante con globos de agua: pasan globos sin reventarlos.',
        ],
        consejos: [
          'Aumenta la distancia entre participantes para mayor dificultad.',
          'Debriefing: ¿Cómo mejoraron la técnica durante el ejercicio?',
          '¿Quién coordinó el ritmo del equipo?',
        ],
        icono: '💧',
      },
    ];
  }
}
